"""
Constants used across the parking management system.
"""

# Database status constants
STATUS_INSIDE = 1
STATUS_COMPLETED = 2
STATUS_INVALID = 99

# File paths
ERROR_LOG_FILE = "error_log.txt"

# GPIO pins
GREEN_LED_PIN = 23
RED_LED_PIN = 24 # Assuming a red LED is on this pin

# Event types
EVENT_TYPE_IN = "IN"
EVENT_TYPE_OUT = "OUT"
EVENT_TYPE_FAIL_IN = "FAIL_IN"
EVENT_TYPE_FAIL_OUT = "FAIL_OUT"
EVENT_TYPE_MANUAL_OUT = "MANUAL_OUT"

# Status events
STATUS_SUCCESS = "SUCCESS"
STATUS_NO_PLATE_DETECTED = "NO_PLATE_DETECTED"
STATUS_PLATE_MISMATCH = "PLATE_MISMATCH"
STATUS_ALREADY_INSIDE_DIFF_RFID = "ALREADY_INSIDE_DIFF_RFID"
